backend:
   name: git-gateway
   branch: master 

   menu: 
   - name: "menu"
     label: "Menu"     
     create: true     
     fields: 
      - { label: "Name", name: "name", widget: "string", required: "true" }
      - { label: "Url", name: "url", widget: "string" }