backend:
   name: git-gateway
   branch: master 

media_folder: "static/uploads"
public_folder: "uploads"

collections: 
  - name: "menu"
     label: "Menu"     
     create: true     
     fields: 
      - { label: "Name", name: "name", widget: "string", required: "true" }
      - { label: "Url", name: "url", widget: "string" }