backend:
   name: git-gateway
   branch: master 

media_folder: "static/uploads"
public_folder: "uploads"

collections: 
  - name: "home"
    label: "Home Label" 
    folder: "content"    
    create: true     
    fields: 
     - { label: "Home", name: "home", widget: "string", required: true }